# Generated by Django 5.1.6 on 2025-02-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('published_at', models.DateTimeField(verbose_name='發佈時間')),
                ('source_name', models.CharField(max_length=100, verbose_name='來源')),
            ],
            options={
                'verbose_name': '新聞文章',
                'verbose_name_plural': '新聞文章',
                'ordering': ['-published_at'],
            },
        ),
    ]
